//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Client
    {
        public int id { get; set; }
        public string description { get; set; }
        public System.DateTime note_timestamp { get; set; }
        public Nullable<int> id_issue { get; set; }
        public string report_number { get; set; }
    
        public virtual Issue_Client Issue_Client { get; set; }
    }
}
