//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue_Client()
        {
            this.Comment_Client = new HashSet<Comment_Client>();
        }
    
        public int id { get; set; }
        public string report_number { get; set; }
        public System.DateTime register_timestamp { get; set; }
        public string address { get; set; }
        public string contact_phone { get; set; }
        public string contact_email { get; set; }
        public string status { get; set; }
        public string support_user_asigned { get; set; }
        public Nullable<int> id_user { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Client> Comment_Client { get; set; }
        public virtual User_Client User_Client { get; set; }
    }
}
