//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment_Client> Comment_Client { get; set; }
        public virtual DbSet<Issue_Client> Issue_Client { get; set; }
        public virtual DbSet<Issue_Support> Issue_Support { get; set; }
        public virtual DbSet<Notes_Support> Notes_Support { get; set; }
        public virtual DbSet<Supervisor_Support> Supervisor_Support { get; set; }
        public virtual DbSet<Supporter_Support> Supporter_Support { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Client> User_Client { get; set; }
    }
}
