//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supporter_Support
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supporter_Support()
        {
            this.Issue_Support = new HashSet<Issue_Support>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string first_surname { get; set; }
        public string second_surname { get; set; }
        public string email { get; set; }
        public Nullable<int> id_supervisor { get; set; }
        public string password { get; set; }
        public Nullable<int> television { get; set; }
        public Nullable<int> mobile_phone { get; set; }
        public Nullable<int> telephone { get; set; }
        public Nullable<int> internet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Support> Issue_Support { get; set; }
        public virtual Supervisor_Support Supervisor_Support { get; set; }
    }
}
