//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HekpDeskSupportNGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue_Client()
        {
            this.Commets_Client = new HashSet<Commets_Client>();
        }
    
        public int id { get; set; }
        public string report_number { get; set; }
        public System.DateTime register_timestamp { get; set; }
        public string address { get; set; }
        public string contact_phone { get; set; }
        public string contact_email { get; set; }
        public string status { get; set; }
        public string support_user_asigned { get; set; }
        public int id_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commets_Client> Commets_Client { get; set; }
        public virtual User_Client User_Client { get; set; }
    }
}
