//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HekpDeskSupportNGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Support
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int is_supervisor { get; set; }
    }
}
