//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HekpDeskSupportNGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes_Support
    {
        public int id { get; set; }
        public string description { get; set; }
        public System.DateTime note_timestamp { get; set; }
        public int id_issue { get; set; }
    
        public virtual Issue_Support Issue_Support { get; set; }
    }
}
