//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supporter_Support
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supporter_Support()
        {
            this.Issue_Support = new HashSet<Issue_Support>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string first_surname { get; set; }
        public string second_surname { get; set; }
        public string email { get; set; }
        public Nullable<int> id_supervisor { get; set; }
        public string password { get; set; }
        public Nullable<int> television { get; set; }
        public Nullable<int> mobile_phone { get; set; }
        public Nullable<int> telephone { get; set; }
        public Nullable<int> internet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Support> Issue_Support { get; set; }
        public virtual Supervisor_Support Supervisor_Support { get; set; }
    }
}
